### ISSUE TITLE
Pls add icon_link_to

### ISSUE THREAD

**Issue by olimart** [hoangnghiem/rails_bootstrap_helper#1]
def icon_link_to(text, url, options)
    icon = options.delete(:icon) if options.has_key?(:icon)
    icon_tag = ''
    if icon
      icon_klass = ["icon-#{icon}"]
      if options.has_key?(:white)
        icon_klass << ["icon-white"]
        options.delete(:white)
      end
      icon_tag = content_tag(:i, '', :class => icon_klass.join(' '))
    end
    link_to (icon_tag + " #{text}").html_safe, url, options
  end

**Comment by hoangnghiem** [comment]
icon_link_to added
